### ISSUE TITLE
Source mapping URL, common.js

### ISSUE THREAD

**Issue by rogerlos** [kee-org/browser-addon#121] opened 2017-12-07 19:46 UTC
```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://[hash removed]/common/common.js
Source Map URL: common.js.map
```

The hash points to:

```
jar:file:///C:/Users/me/AppData/Roaming/Mozilla/Firefox/Profiles/
riaxctmo.default/extensions/keefox@chris.tomlinson.xpi!/
```

the final line of Kee's common.js is:

```
//# sourceMappingURL=common.js.map
```

If I do not have the Firefox extension Greasemonkey enabled, the console is silent. But if I enable GM, the aforementioned console warning shows up. I'm not certain who is "at fault" here. Also pinging the GM folks.

**Comment by RenierZA** [comment] 2018-01-12 07:36
I keep getting this error (and the logging initialized message) in my console.  I don't have GreaseMonkey installed.
![image](https://user-images.githubusercontent.com/1150349/34864241-f920bc72-f77b-11e7-86bb-c6d7fdaec2c3.png)

**Comment by luckyrat** [comment] 2018-01-20 11:21
I expect this to be caused by the fact that I was intentionally not shipping source maps in the production/stable Kee release but still referencing sourcemaps from each js file. Should therefore be fixed in the next stable release (but has no effect other than noise in the console until then).

**Comment by luckyrat** [comment] 2018-01-21 21:49
On further inspection, while there was a bug in Kee, Firefox also has a lot of bugs relating to sourcemapping and these need to be addressed by Mozilla before these console warnings will go away from the beta version of Kee.

https://docs.google.com/document/d/1lnrhOs4IHW9W6vxCG_96f553GAaudsLIKwuVJ3Wd5pY/edit#heading=h.zd69njz0cw62

The stable version should be OK though, as will the Beta version when running in Chrome. I'll reopen and block this even though the scope of the issue is now much narrower.

**Comment by luckyrat** [comment] 2020-10-23 12:20
Source map support is still very unreliable but it has improved a bit in the past few years and this issue has been resolved by Mozilla.

**Closed by luckyrat** 2020-10-23 12:20 UTC
Labels: blocked, bug
