### ISSUE TITLE
Toolbar button popup formatting

### ISSUE THREAD

**Issue by Dimas-sc** [kee-org/browser-addon#57] opened 2017-11-09 08:04 UTC
Sorry if it isn't a issue, I didn't know where to post it.

The toolbar button popup are always showing this:
![Screenshot](https://i.imgur.com/U1nQa0i.png)
Is this the expected behavior? When logged to the database is always showing this, no functionality and no styled text.

2.0 Beta 3

**Comment by luckyrat** [comment] 2017-11-09 20:33
It's totally an issue. I've not had time to even think about styling that panel yet... I've got it to work and had to move on to more serious issues. I am planning to look at it over the weekend if nothing more serious comes up... unless someone else wants to grab this and submit a pull request in the meantime.

**Comment by t0lik** [comment] 2017-11-12 14:20
How about this?

![default](https://user-images.githubusercontent.com/400628/32699845-08be4408-c7cd-11e7-9f0c-10cdaccb1552.png)

The menu item "Generate new password" is under mouse.
I also propose that notifications should be below main menu items as they are more dynamical content. 

How can I test this popup with some notifications?

**Comment by t0lik** [comment] 2017-11-12 15:21
Or this one:

![default](https://user-images.githubusercontent.com/400628/32700429-3b9048fa-c7d6-11e7-95ba-7155b27072bc.png)

**Comment by luckyrat** [comment] 2017-11-12 16:50
I think the notifications should appear near the top since they are typically much more important than the links. The argument of dynamic vs static content would be stronger if we're dealing with a persistent interface but the popup is very transient and the exact links to display will change between invocations too.

I think I like the 2nd one better because we also need to allow space for the notifications to optionally appear before the list of action links and that option has a more balanced feel to it. Those notifications will need restyling too but as long as this change to the rest of the dialog doesn't make them look any worse, we can look at doing that in a 2nd PR.

One way to test the notifications is to save an update to a password (and ensure the option to "Display the "Password successfully updated" notification" is enabled). Another way would be to intentionally misconfigure the KPRPC security settings so that Kee treats the KeePass end of the connection as too insecure to connect to.

**Comment by luckyrat** [comment] 2017-11-12 17:05
If you're gonna take a look at the notification styles now, please can you also allow for a cross/close/dismiss button at the top right?

The update password notification is a good example of where I need to add support for this feature because the user may just want to dismiss the current notification but without clicking the action button to permanently stop showing the message.

Thanks.

**Comment by t0lik** [comment] 2017-11-12 18:53
> One way to test the notifications is to save an update to a password (and ensure the option to "Display the "Password successfully updated" notification" is enabled).

I couldn't reproduce this. Please explain how to do this step by step.

**Comment by luckyrat** [comment] 2017-11-12 18:58
1. go to Kee options
2. scroll down and enable the "Password successfully updated" notification" setting
3. load a page (e.g. https://tutorial-addon.kee.pm/step3 )
4. Put a username and password in the form and submit it
5. Go to the Kee browser action popup and click "Save latest login"
6. Click on the "Update" tab
7. Select an entry to update
8. Click the "Update" button
9. Notification will now appear

**Comment by luckyrat** [comment] 2017-11-13 18:23
I think we can close this now. There may well be some follow-up issues to improve specific areas but @t0lik has done a great job of getting this into a decent enough state for the initial release. Thanks!

**Closed by luckyrat** 2017-11-13 18:23 UTC
