### ISSUE TITLE
Authorization prompt is blank 

### ISSUE THREAD

**Issue by nailyk-fr** [kee-org/browser-addon#39] opened 2017-10-11 08:27 UTC
Just installed keefox from github releases + keepassplugin from github too. 
The 'Authorize a new connection' window is blank. Mouse change in some location of the window. 

![capture d ecran - 11102017 - 10 22 00](https://user-images.githubusercontent.com/16372405/31429499-86367aae-ae6e-11e7-8f5f-69c13f306c1b.png)

Debian 8 x64.
Firefox Nightly 58.0a1. 

No idea where to find logs. 
Could it be related to https://github.com/kee-org/browser-addon/issues/22 ?

**Comment by nailyk-fr** [comment] 2017-10-11 08:29
This appear into browser console: 
```
TypeError: invalid 'in' operand browser[Learn More]  tabbrowser.xml:2431:1
	_insertBrowser chrome://browser/content/tabbrowser.xml:2431:1
	getRelatedElement chrome://browser/content/tabbrowser.xml:7149:11
	set_selectedIndex chrome://global/content/bindings/tabbox.xml:406:31
	tabs_XBL_Constructor chrome://global/content/bindings/tabbox.xml:275:13
	<anonymous> chrome://browser/content/tabbrowser.xml:46:9
	_updateNewTabVisibility chrome://browser/content/tabbrowser.xml:5829:15
	tabbrowser_XBL_Constructor chrome://browser/content/tabbrowser.xml:5886:11
```

**Comment by gojpdchx** [comment] 2017-10-12 04:25
What if you maximize the "Authorize a new connection" window?

**Comment by nailyk-fr** [comment] 2017-10-12 06:20
Good catch! 
Now working fine. 
What log can I provide to help debugging this?

**Comment by luckyrat** [comment] 2017-10-12 20:08
@nailyk-fr This is a Firefox bug. Please search on https://bugzilla.mozilla.org for anything similar and raise a new bug if you can't find anything, including the TypeError stack trace and the workaround to help them diagnose the problem.

If anyone knows of an earlier version nightly that worked, it would be worth including that information too.

FWIW, I've just tested on Windows Nightly and it works just fine.

**Comment by Marcosdw** [comment] 2017-11-02 09:11
This bug is always present in Keefox 2.0.0 alpha18

**Comment by elgonzo** [comment] 2017-11-08 01:04
I am affected by this issue too (Keefox 2.0.0.20b2).

The real bummer here is that this issue is known to Mozilla and has been declared a "**won't fix**" (https://bugzilla.mozilla.org/show_bug.cgi?id=1402703.).

(FYI: the underlying cause of the issue has been identified to be a race condition. Which means, KeeFox running stable on some setups with Windows Nightly unfortunately doesn't mean the problem is gone.)

So, where does this leave Keefox...?

**Comment by luckyrat** [comment] 2017-11-09 00:10
I think there's some confusion - the chrome=no behaviour seems to be forced upon WebExtensions opening popups, or at least the default behaviour. So on that basis they seem to be suggesting that their WebExtensions implementation is incorrect.

Regardless, I'm considering switching to tabs for this popup as part of #56 so if we go ahead with that change, this issue would become academic.

For anyone interested, this is the (typescript) code in Kee:

```
const createData = {
            type: "popup",
            url: "/dialogs/SRP.html",
            width: 700,
            height: 550
        };
        const creating = (browser as any).windows.create(createData);
```

**Comment by Marcosdw** [comment] 2017-11-09 08:17
When will you fix the problem in the next beta?

**Comment by Marcosdw** [comment] 2017-11-12 15:08
This bug is always present in Keefox 2.0.0.22b4 for authentification .htaccess

**Comment by luckyrat** [comment] 2017-11-12 23:01
I've created a new issue for the network auth problem.

**Closed by luckyrat** 2017-11-12 23:01 UTC
