### ISSUE TITLE
Firefox's "remembered list" overlaps Kee's logins list

### ISSUE THREAD

**Issue by LucasMetal** [kee-org/browser-addon#78] opened 2017-11-14 05:26 UTC
Kee 2.0.0.24b6
FF 57.0 64bits

Hi!

Thanks for the hard work, AWESOME extension. I've been following the migration closely looking for ways to help, here are my first two cents.

Steps:
- Navigate to a page for which you have logins available, and for which also Firefox remembers some previous values for the login fields (username, email, etc)
- Click the Kee button on the username field
- The Firefox list of remembered values will overlap the Kee logins list, forcing you to click again a couple of times to be able to choose the first login of the Kee list. It's not a big issue but it turns annoying during the whole day.

![image](https://user-images.githubusercontent.com/3739957/32764202-06b25f2a-c8e3-11e7-85fa-475c0e4f1d08.png)

Thanks!

**Comment by LucasMetal** [comment] 2017-11-14 05:34
Well, while playing around a bit more after reporting this I realized that if I click on the password field instead of the username one the issue doesn't happen because the browser doesn't remember passwords of course.
Anyway we could consider this a rough edge, but nothing serious for sure.

Thanks again!

**Comment by Park0** [comment] 2017-12-07 06:58
I disagree about the impact of this misbehavior. When u have multiple logins for the same site u can select one of them. This is done in the username field. So you will click on the kee icon it will show as usual. Now select login2. Login logout. Do the same try to select another login. Both Kee and the remembered list will show. The remembered list will block part of the kee popup. If u have multiple logins this lost can get long.  

The password field could fix this. But i think most people will click on the user without thinking about it.

**Comment by jalefkowit** [comment] 2017-12-11 19:52
I've run into this one too. Not a terrible thing, but definitely an annoyance.

**Comment by manuc66** [comment] 2018-01-24 21:57
Maybe it could get fixed by injecting a `autocomplete="off"` on the input tag.

**Comment by luckyrat** [comment] 2018-02-01 21:40
Can anyone replicate this in Firefox 59 (beta) and Kee 2.1.x?

Pretty sure I've not made any changes in Kee which could have altered this behaviour but despite seeing it once or twice myself last year, I've yet to be able to reproduce it over the past few weeks so either Firefox have changed something or it only affects a small number of websites... if the latter, some example URLs would be very helpful so I can explore @manuc66 's good suggestion.

I've just created some new [guidelines ](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548)to help us all keep each discussion focussed in one place whenever possible. Although this issue fits into the category of discussion that would have been best held on the community forum rather than GitHub issues, I'm reasonably confident that there is going to be fast enough resolution to this issue to make it not worthwhile migrating the information at this point so let's make an exception this time and keep discussing here.

**Comment by manuc66** [comment] 2018-02-01 23:25
@luckyrat I can reproduce it on FF 60.0a1 (2018-02-01) (64 bits) 
![image](https://user-images.githubusercontent.com/5827164/35708615-358e5a00-07af-11e8-97d0-b454a8e637ac.png)
I was using Kee 2.1.26

**Comment by luckyrat** [comment] 2018-02-02 00:13
Ah thanks. Yes, I can now reproduce as long as the focus is already on an empty input field. I'll investigate further tomorrow.

**Closed** 2018-02-05 22:09 UTC

**Comment by luckyrat** [comment] 2018-02-05 22:29
autocomplete=off did prevent the autofill dropdown from appearing but it isn't possible to invoke this attribute change at a time which can ensure that autofill can still be used on non-login forms that Kee has attached an icon to.

Since the icon attachment (and more generally the form detection) algorithm aims for false positives rather false negatives, it is important for wider browser usability that we don't destroy the built-in form filling feature by disabling it before we know that the user intends to interact with Kee within that particular form field.

I have instead resolved this issue by redirecting keyboard focus to the matched logins panel when it loads, thus causing Firefox (and Chrome) to remove the autofill dropdown shortly after it has been displayed.
