### ISSUE TITLE
Feature Request - Regex or Partial Name/ID matches

### ISSUE THREAD

**Issue by amiga-500** [kee-org/browser-addon#171] opened 2018-04-03 20:34 UTC
Using Kee v2.3.19.1

Was wondering...Some banks like to postfix a random identifier to id/class attribute which makes it difficult for Kee to spot.  For example, CIBC passowrd input box is: id="password_4848c4" ... when you refresh the page it is then "id=password_d837g".  As you can see the prefix "password_" stays the same but the postfix part changes.  

It would be very useful if Kee support regex or partial matching for id or class attributes.

**Comment by luckyrat** [comment] 2018-04-10 10:05
This is a duplicate of https://github.com/kee-org/browser-addon/issues/67

I've given it a better title now so hopefully will be easier for others to find in future.

**Closed by luckyrat** 2018-04-10 10:05 UTC
