### ISSUE TITLE
Search missing

### ISSUE THREAD

**Issue by chriss2142** [kee-org/browser-addon#82] opened 2017-11-15 08:42 UTC
It seems that the old search field is removed.
I used this feature a lot to open pages or search for logins if the autodetect is not possible.
For me this means I have to switch to Keepass and than back to Firefox a lot.

I hope you can bring the search field als option back
Thanks for this plugin

**Comment by auanasgheps** [comment] 2017-11-15 10:11
Please see https://github.com/kee-org/KeeFox/issues/823

**Comment by luckyrat** [comment] 2017-11-15 19:12
Duplicate of #7

**Closed by luckyrat** 2017-11-15 19:12 UTC
