### ISSUE TITLE
The "Save this login" popup notification appears too often

### ISSUE THREAD

**Issue by dertuxmalwieder** [kee-org/browser-addon#75] opened 2017-11-13 12:04 UTC
The notification that claims that it would only appear "a small number of times" appears too often.

Example: The banking site I use for trading stocks has saved login data in my KeePass. Kee knows that and displays the icon accordingly after the fields have been filled. [Screenshot](https://i.imgur.com/SLRp8i2.png) (rectangles added by me).

After clicking the log-in button, I still get the "do you want to save the login?" notification every time.

**Comment by luckyrat** [comment] 2017-11-13 12:07
Duplicate of #74

**Closed by luckyrat** 2017-11-13 12:07 UTC
