### ISSUE TITLE
Infinite authorization windows

### ISSUE THREAD

**Issue by ashkitten** [kee-org/browser-addon#22] opened 2017-08-28 14:29 UTC
When I installed the browser extension and KeepassRPC, I got an infinite number of authorization windows appearing, without any of them actually having anything inside.

**Comment by luckyrat** [comment] 2017-08-30 18:13
Can you see if there are any logs in Kee or KeePassRPC and paste them here? I suspect this could be a somewhat over-zealous side-effect of a failing SRP handshake. Perhaps KeePassRPC now fails to detect aborted handshakes or perhaps this is not a new problem in KPRPC but is instead an indication of a new problem with the SRP handshake in Kee.

What operating system, Firefox, Kee, KeePass and KeePassRPC versions are you running?

**Comment by NoXPhasma** [comment] 2017-08-30 18:27
I have the same issue.

- Firefox Nightly
- Linux Mint 18.2
- Kee 2.0.0.5
- KeePass 2.36
- KeePassRPC 1.7.0.0

KeePassRPC Log: https://gist.github.com/NoXPhasma/53b410df465f90bf98cb6ce4fd6c0dd5

Kee does not create a folder in the Firefox profile and I couldn't find any log file of it.

**Comment by luckyrat** [comment] 2017-08-30 18:32
Does upgrading to KeePassRPC 1.7.2.0 fix the problem?

**Comment by luckyrat** [comment] 2017-08-30 18:35
Kee isn't allowed to log to disk so you'd have to use the browser console. You can select all and copy but it'll bring along lots of stuff unrelated to Kee so it's not ideal. I've yet to hear from Mozilla what approach they recommend now that they have banned local disk logging but I'm sure we can refine these instructions in the coming weeks.

**Comment by NoXPhasma** [comment] 2017-08-30 18:38
I have no idea where I can get 1.7.2.0. I'm using the [KeePass-Plugins PPA](https://launchpad.net/~dlech/+archive/ubuntu/keepass2-plugins) and that only provides 1.7.0.0.

**Comment by NoXPhasma** [comment] 2017-08-30 18:48
Yes, that actually works! I got the Code window of KeePass and also the window of Kee to add that.

The Kee icon shows it's connected but I don't get any passwords on sites which are in the database.
![unbenannt](https://user-images.githubusercontent.com/7719590/29889457-87bf20bc-8dc4-11e7-9c61-442dae8bf250.png)

**Comment by luckyrat** [comment] 2017-08-30 19:42
Glad to hear that it worked.

> I guess this is the new way to use it?

Yeah that's right. While technically possible (I think), keeping the contents of the popup up to date with the specific details of the forms on the page is much more complex than the current approach and would therefore be too risky to attempt this year. Besides, having the passwords closer to the context in which they are used will allow for some future improvements to form filling functionality that we can flesh out once v 2.0 is stable.

I'm thinking about including a link in the popup to the new tutorial at https://tutorial-addon.kee.pm once it's a bit better tested. Even the "Help Centre" page doesn't get you there now but I suspect a direct link might help ease the transition from v1 to v2... along with the documentation I can get started on once the styles are more consistent and less jarring on the eye (although it's interesting that your screenshot from Linux is far closer to the expected styles as per Google Chrome than those on my Windows dev machine).

**Comment by NoXPhasma** [comment] 2017-08-30 19:50
I'm using a dark desktop theme and a dark Firefox theme, if you are talking about the theme. If not, I have no Idea how it looks on Windows or in Chrome :)

Though, I would prefer it wouldn't be that hard to read. maybe you can add a way to add userstyles inside the addon? Since we cannot Style it anymore with Addons like Stylus, we really need a option inside the addon for that. Although, I would prefer if Mozilla would take care about that (dark firefox theme == different drop down menus of addons).

**Comment by luckyrat** [comment] 2017-08-30 20:03
It's the font face that stands out in my opinion but maybe I'm just fussy about these things :-)

I'll do what I can to work with any new theming support in Firefox whether via Firefox itself or popular addons, although I can't promise the work (when/if it becomes clear what that work is) will be given a high priority for the initial 2.0 launch.

**Comment by NoXPhasma** [comment] 2017-08-30 20:05
The font is DejaVu Sans, that's default on Firefox for Linux.

**Comment by luckyrat** [comment] 2017-08-31 20:29
Weird. I can't recall ever seeing a serif font in the Firefox UI on Windows so quite why the Times New Roman default is coming through as default in the Kee interface is a mystery. I'll take a closer look soon anyway though.

**Comment by gojpdchx** [comment] 2017-09-05 03:19
> Doh, I found out that Kee doesn't provide a list anymore, but a Menu entry in the contextmenu of the input fields. I guess this is the new way to use it?

> Yeah that's right. While technically possible (I think) ... ... ...

@luckyrat 

I am using Kee 2.0.0 alpha5, KeePassRPC 1.7.2.0 and KeePass 2.36 with the latest version of Firefox Nightly. Kee is able to connect to my database. However, when I right click on the input fields, choose "Kee" and then "Find matching logins", there is no effect. In other words, I cannot find a way to choose a matching entry and have Kee auto-input the details for me.

If I use KeeFox 1.7.2, KeePassRPC 1.7.2.0 and KeePass 2.36 with Firefox Nightly 56.0 (KeePass database content being the same), I can still use the traditional way and the plugin works as intended. I can click on the KeeFox toolbar button and the matching logins will be displayed. After choosing an entry, KeeFox will auto-input the username and password in the corresponding fields.

Could you please tell me what steps are needed to have Kee display the matching logins and auto-input login form fields? Do I need to tweak my database so that Kee will be able to "see" my entries? Thank you.

**Comment by luckyrat** [comment] 2017-09-05 16:47
Do you see the Kee icon in the form field you want to fill in? Just click
that. If not, there may be a bug that means this specific form is no longer
found by v2.

**Comment by gojpdchx** [comment] 2017-09-05 23:51
@luckyrat 
Thank you. **For unknown reason**, I noticed that when Kee is used _for the first time_ after the (every) start of browser, some time is needed before it will actually search for matching logins and display the icon in the form field. In addition, if I activate the option "Offer to save passwords", a "save entry" dialog pops out after using Kee to login, despite the fact that the password is unchanged (at the submission of the form).

Steps to reproduce:
1. Open Firefox Nightly and allow all plugins and add-ons to finish loading.
2. Navigate to a webpage that contains login form field, e.g. GitHub.
3. In the form fields, the Kee icon is not displayed. Clicking "Find matching logins" in the context menu has no effect.
4. Wait for some time (15 seconds) and/or switch to another tab.
5. The Kee icon is displayed. The form fields are filled automatically if there is only one matching login.
- - - - -
6. Use Kee to login, i.e. there is a matching entry in the database already, with the correct username and password.
7. After logging in, a "save entry" dialog pops out.
- - - - -
8. Open other webpages that contain login form fields.
9. The Kee icon is immediately displayed. Entries are filled automatically at once.

**Comment by luckyrat** [comment] 2017-09-07 21:06
Thanks for the info @gojpdchx . It may be related to the work we still need to do in #10 but I don't fully understand that yet so it'll take a while to be sure. Possibly relates to whatever the active tab is when the browser starts.

**Comment by xamphear** [comment] 2017-09-21 13:54
I had this problem but it went away after I changed the two security settings in KeePass's KeePassRPC options from "Low" to "Medium". I think I had set them to "Low" at some point when troubleshooting an issue.

**Comment by merky1** [comment] 2017-11-08 01:17
I am having this problem currently.  Browser console only reads  : 
In browser content page script, received message from background script

Kee 2.0.0.20b2
KeePassRpc 1.7.3.0

**Comment by luckyrat** [comment] 2017-11-09 22:50
Do you see any notification in the Kee main popup panel on the toolbar?

Or anything in the background script console? (access by going to about:debugging, enabling add-on debugging and then clicking the "debug" link for Kee)

**Comment by merky1** [comment] 2017-11-10 02:00
Focus changed for id: 3  common.js:171:17
Focus changed for id: -1  common.js:171:17
Focus changed for id: 3  common.js:171:17
The connection to ws://127.0.0.1:12546/ was interrupted while the page was loading.  app.js:251:29
Websocket connection error  common.js:171:17
Websocket connection error end  common.js:171:17
Pausing Kee.  common.js:171:17
Kee paused.  common.js:180:17
Websocket connection closed  common.js:171:17
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://0eeee0ed-8933-46ed-b198-5a9c9344f8d1/background/app.js
Source Map URL: app.js.map[Learn More]  (unknown)
Speculatively trying to open a webSocket connection  common.js:171:17
Attempting to connect to RPC server webSocket.  common.js:171:17
Trying to open a webSocket connection  common.js:171:17
Websocket connection opened  common.js:180:17
received message from web socket  common.js:171:17
Focus changed for id: -1  common.js:171:17
Tab activated with id: 4  common.js:171:17
Logging system initialised at Thu Nov 09 2017 20:59:34 GMT-0500 (Eastern Standard Time)  common.js:180:17
Logging system config updated at Thu Nov 09 2017 20:59:34 GMT-0500 (Eastern Standard Time)  common.js:180:17
Focus changed for id: 56  common.js:171:17
Focus changed for id: -1  common.js:171:17
received message from web socket common.js:171:17
Kee must restart the authorisation process. Further info may follow: Already authorised  common.js:189:17
Pausing Kee.  common.js:171:17
Kee paused.  common.js:180:17
Websocket connection closed  common.js:171:17
Sending a JSON-RPC request  common.js:171:17
starting webcrypto encryption  common.js:171:17
JSON-RPC request could not be sent. Expect an async error soon.  common.js:189:17
Refresh of Kee's view of the KeePass database initiated.  common.js:171:17
Sending a JSON-RPC request  common.js:171:17
starting webcrypto encryption  common.js:171:17
JSON-RPC request could not be sent. Expect an async error soon.  common.js:189:17
An error occurred in KeePassRPC object id: 2 with this message: error and this error: [object Object] and this error message: Send failure. Maybe the server went away?  common.js:198:17
An error occurred in KeePassRPC object id: 3 with this message: error and this error: [object Object] and this error message: Send failure. Maybe the server went away?  common.js:198:17
HTTP connection did not timeout. We will now attempt a web socket connection.  common.js:171:17
Attempting to connect to RPC server webSocket.  common.js:171:17
Trying to open a webSocket connection  common.js:171:17
Websocket connection opened  common.js:180:17
received message from web socket  common.js:171:17
Tab activated with id: 5  common.js:171:17
Logging system initialised at Thu Nov 09 2017 20:59:58 GMT-0500 (Eastern Standard Time)  common.js:180:17
Logging system config updated at Thu Nov 09 2017 20:59:58 GMT-0500 (Eastern Standard Time)  common.js:180:17

**Comment by luckyrat** [comment] 2017-11-13 00:13
> JSON-RPC request could not be sent. Expect an async error soon. common.js:189:17
> An error occurred in KeePassRPC object id: 2 with this message: error and this error: [object Object] and this error message: Send failure. Maybe the server went away? common.js:198:17

Those messages are unusual. Do you have any other plugins installed in KeePass? What about other add-ons in Firefox?

What version of Firefox are you using?

What operating system are you on?

Do you have any other security software installed on the machine?

**Comment by merky1** [comment] 2017-11-13 13:11
First, problem resolved with latest FireFox beta.  Kee working as designed.

Second : 

Firefox 57beta
Kee 2.0.023b5
Adblock plus 3.0.1
Avast

**Comment by luckyrat** [comment] 2017-11-13 14:16
Good to hear it is working properly now so I'll close this issue.

**Closed by luckyrat** 2017-11-13 14:16 UTC
