### ISSUE TITLE
Support for KeeWeb

### ISSUE THREAD

**Issue by Trollwut** [kee-org/browser-addon#101] opened 2017-11-21 20:59 UTC
Hi folks!

Your project seems to be the best when it comes to KeePass integration. Now I'm using [KeeWeb](https://keeweb.info/) as my frontend, which connects to browser extensions with it's plugin [KeeWebHTTP](https://plugins.keeweb.info/plugins/keewebhttp/)

For me, `Kee` doesn't connect to my KeeWeb. Is there a chance to get support for it?

**Comment by muchtall** [comment] 2018-01-15 19:20
I agree that support for this would be good. I have a number of people I share databases with that use non-Windows platforms, and KeeWeb is their manager of of choice as KeePass doesn't work as well on Mac/Linux as it does on Windows. For them, chromeIPass is the only option, albeit inferior. Having the slick browser integration of Kee in combination with the consistent cross-platform UI of KeeWeb would significantly increase the peer/wife acceptance factor of using KeePass for group password sharing.

**Comment by lammel** [comment] 2018-01-29 13:51
There is also an [issue open for KeeWeb](https://github.com/keeweb/keeweb/issues/84). The issue is closed already, so it seems there is no support for KeePassRPC planned in any way.

**Comment by luckyrat** [comment] 2019-03-01 17:30
I've recently [announced Kee Vault](https://forum.kee.pm/t/kee-vault-and-kee-version-3-0/2025), which has a visible interface that is based upon KeeWeb. It comes with built-in support for the Kee browser extension. It utilises a similar link to the one with KeePass but runs entirely within the web browser so I've been able to develop a solution that doesn't rely upon the existing C# plugin.

As you've probably already realised, getting the Kee addon to work in KeeWeb would require a redevelopment of the C# plugin per kee-org/keepassrpc#25  , which can't happen so I'll close this issue now as being out of scope for this project.

**Closed by luckyrat** 2019-03-01 17:30 UTC
