### ISSUE TITLE
Lots of freezes and CPU usage with Kee alpha 13-14 (Firefox 57.0b7)

### ISSUE THREAD

**Issue by Gwend4l** [kee-org/browser-addon#40] opened 2017-10-16 09:03 UTC
With Firefox 57.0b7, I get lots of freezes when Kee alpha 13-14 is enabled. During a freeze, the CPU usage of Firefox skyrockets. This maybe happen when loading a tab, but I am really not sure.

Note that when there is no freeze, I managed to use Kee successfully.

**Comment by luckyrat** [comment] 2017-10-17 21:07
Duplicate of #27

**Closed by luckyrat** 2017-10-17 21:07 UTC
