### ISSUE TITLE
Firefox 57.0 Quantum - A script in the extension 'Kee' is causing Firefox to slow down [Learn More...]

### ISSUE THREAD

**Issue by dreamcat4** [kee-org/browser-addon#111] opened 2017-11-27 09:38 UTC
* Kee 2.0.0.25
* Firefox 57.0 Quantum, on win10

Hi there.
A single yellow bar keeps flashing up in some websites. Which says:

```
A script in the extension 'Kee' is causing Firefox to slow down [Learn More...]
```
And clicking the link 'Learn More' directs to this page: https://support.mozilla.org/en-US/kb/warning-unresponsive-script#w_other-causes

Then it dissapears again. Re-appears sporadically etc. This was happening for me on irccloud.com. I also noticed that the text entry input field for the website became completely unresponsive. There was no flashing cursor, and it would not update in a very long time.

I think whatever issues Kee has been having are still very much present. And maybe it relates to Kee checking text entry fields for password completion?

To reproduce this should be fairly easy. For example by getting an account on irccloud.com and joining a bunch of channels. Or otherwise trying other websites which already are known to trigger similar issues.

If you need any more debugging information, then please provide those necessary instructions.

**Comment by dreamcat4** [comment] 2017-11-27 09:52
Ah interesting...

The yellow bar has some buttons on the very right side that say 'Temporarily Disable Addon for this Site' and 'Stop Scripts' or 'Wait'. However the yellow bar flashes up / dissapears far too quickly to actually click on those buttons.

When I do 'performance' measurement start / stop. Almost the entire graph is filled up with thousands of tiny 'Minor GC' events. For example:

Minor GC
Duration: 0.62 ms
Cause: FULL_SLOT_BUFFER
Type: Nursery Collection

Then (most times) for every 5 of those in a row, there is 1:

Non-incremental GC
Duration: 5.03 ms
Cause: Too Many Allocations
Non-incremental Cause: GCBytesTrigger

Or otherwise there is different numbers of each type, with the Minor GC being much more common.

**Comment by jaredb7** [comment] 2018-01-14 00:55
I'm also getting this issue, have only noticed it on Facebook if I'm scrolling news feeds / page posts for a while. Firefox seems to hang then the yellow bar will show for 1 second, disappear and things appear to run normally for a little while. Then the process repeats.

During this time memory & usage of one of the firefox processes is higher than the rest, 12% CPU (in a 8 core setup) and 2-3GB of memory. This happens over a number of hours.

I'm with @dreamcat4 though, I think it may be the continuous checking of text entry fields, which on facebook there can be quite a few, if you're scrolling a large page of posts there's one (comment) for every post.
Haven't noticed the issue on other sites at current.

**Comment by dreamcat4** [comment] 2018-01-19 05:10
Hi @luckyrat - if you need any more debugging type logs or information from the browser, please let us know hot to gather that. So we can provide you a more complete / accurate bug report. Many thanks. 

Hope you can get round to looking into this sometime because it is a persistent problem. It always happens for these specific websites, and really hangs the browser pretty badly.

**Comment by luckyrat** [comment] 2018-01-20 11:33
Thanks for the offer @dreamcat4 

It's interesting that this is triggered by irccloud.com since I came across a similar critical bug report for LastPass while perusing Bugzilla the other day. There's no information about what the solution was for them but I suspect I'll have to block Kee from operating on sites which have a large number of form elements. Of course, improving performance of some parts of the form detection algorithm could be worthwhile too but in something where there is an ever-growing number of form fields, that can only get us so far so won't be enough on its own.

I haven't had time to look into it yet but hope that it won't be a huge problem to fix once I get around to it.

I've just created some [new guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548) to help us all keep each discussion focussed in one place whenever possible. Although this issue fits into the category of discussion that would have been best held on the community forum rather than GitHub issues, I'm reasonably confident that there is going to be fast enough resolution to this issue to make it not worthwhile migrating the information at this point so let's make an exception this time and keep discussing here.

**Comment by luckyrat** [comment] 2018-01-29 21:06
Thanks everyone for reporting this.

ircloud.com seems to be a poorly performing website so sites like this are hopefully rather unusual. Regardless of whether Kee is installed, it really struggles with basic functionality like scrolling up and down the page and many interactions are noticeably slow.

Nonetheless, with Kee installed, the poor performance of that site is quite clearly exacerbated and I'm pleased to say that I've made some improvements to Kee that will reduce that impact significantly.

I have now put in some hard limits on the number of forms and the number of fields allowed per form before Kee ignores the page but in my testing on irccloud I don't think these limits are being reached anyway. Your mileage may vary.

The major contributing factor I've seen is the number of potential submit buttons on the page.

There are thousands of potential form submit buttons on the site so it takes a long time to evaluate which ones should be considered the "primary" button for each of the dozen or so forms on the page (so that Kee can attach a listener to those selected buttons and therefore prompt to save a password if you click on them).

I've spent a few days on this so far and have yet to identify any realistic way to avoid processing some of these items in a way that can ensure no reduction in accuracy.

I hope that the many other performance improvements I've made will mean that the practical impact of this remaining inefficiency will be quite rare. I've posted a [news article on the forum](https://forum.kee.pm/t/performance-improvements-in-kee-2-2/678) in case you're interested in more detail.

In terms of the "Kee is slowing down your browser" warning, there is a 5 second limit in recent versions of Firefox after which this warning message is displayed.

I managed to see the message a few times while investigating irccloud.com, but usually only when other processes on my system or other websites were reducing the CPU time available to Kee. I inserted some temporary performance measurements and found that it was easy to get close to that 5 second limit (and a slower system would be affected more significantly).

My initial tests showed me a fairly reproducible delay of around 4000ms in Firefox and 1000ms in Chrome.

All of that time is spent in a part of Kee that essentially blocks the web page from doing anything else at the same time.

The changes I've just put onto master will reduce the time spent in this initial "blocking" phase of Kee operations to around 2-10ms in both browsers. I've split up the process of detecting submit buttons so that this happens separately for each form on the page (the web page can do its own work in between each). Each of these processes can still take 20-100ms but that's still a big improvement on the previous version.

The total time, including detecting the submit buttons on all forms on the page is now down to around 200ms in Chrome and to around 600ms in Firefox.

I'm not sure how Firefox defines "5 seconds". If it's only time spent in one blocking call we should be all good now but if it's total CPU time over 5 seconds there might still be some exceptional websites that can breech that on slow computers - we'll have to investigate that as a separate issue if it ever happens.

These improvements will be included in Kee 2.2 (probably going to be released to the beta channel by next week).

PS: I couldn't reproduce any performance problems on Facebook in any version of Kee.

**Closed by luckyrat** 2018-01-29 21:06 UTC
Labels: bug

**Comment by dreamcat4** [comment] 2018-01-29 22:43
Thank you @luckyrat for these improvements. They are most welcome! After reading your explaination about these difficulties, it is clear you have spent a lot of time on this. I would not say anything about your approach is wrong whatsoever. However it has now ocurred to me that if you were to implement some kind of a URL blacklisting mechanism feature in the future... Then that would additionally also enable affected users. By just stopping Kee from even tying to scan the page in the first place. For those matched blacklisted URLs. Sorry it was just something that only occured to me after reading your detailed explanation today. Before now I just assumed it was some kind of a blocking bug / stuck code path in your extension. It being so new and everything.

Anyhow I'm glad to look forward to trying these improvements as soon as I can upgrade my version of the Kee extension. Thank you!!!

**Comment by luckyrat** [comment] 2018-02-01 21:53
Thanks for the feedback @dreamcat4 . A blacklist feature has occurred to me too but I've decided against it at the moment, primarily because that's a quite drastic way to resolve something that from a user's perspective should "just work". It's an option for the future if we find anything where other approaches aren't feasible although I don't think a full exclusion can be done in Firefox <59 or any version of Chrome (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contentScripts/register is probably what we'd want to use).
