### ISSUE TITLE
Small display bug on https://www.ukqcs.com

### ISSUE THREAD

**Issue by ciborge** [kee-org/browser-addon#208] opened 2018-12-03 06:53 UTC
I noticed that it could be tricky to click on the Kee icon in the login field as the buton is hiden behind a "Forgot password" button.

i don't know if there is really something to be done about it as it is unique about this website but i thought i would leave it here.

https://www.ukqcs.com
http://prntscr.com/lpy2gj

**Comment by luckyrat** [comment] 2019-03-01 17:58
Per the [guidelines](https://forum.kee.pm/t/contributions-bugs-help-and-support-guidelines/548), please search and then post messages like this in our [community forum](https://forum.kee.pm) rather than GitHub so that more people can view and contribute to the discussion. If the result of that discussion is a decision to make a change to the Kee code (e.g. for a new feature / bug fix), we'll create a new issue on GitHub once the details have been finalised.

This is essentially a duplicate of #127 anyway.

**Closed by luckyrat** 2019-03-01 17:58 UTC
