### ISSUE TITLE
browser-polyfill.min.js.map is missing from distribution

### ISSUE THREAD

**Issue by Ythan** [kee-org/browser-addon#314] opened 2022-01-09 06:57 UTC
Hello, the file `/lib/tp/browser-polyfill.min.js.map` is missing from the addon, causing a console error message in Firefox on every page load:

> Source map error: Error: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://****/lib/tp/browser-polyfill.min.js
> Source Map URL: browser-polyfill.min.js.map

If you download [browser-polyfill.min.js.map](https://unpkg.com/webextension-polyfill@0.6.0/dist/browser-polyfill.min.js.map) 0.6.0 and add it in the correct location, it resolves the error. Could you please fix this in a future release?

**Comment by lonix1** [comment] 2022-05-08 00:29
This is very annoying, when doing any work in the browser I keep getting distracted by this error.

Options:
- include source map in extension (worst option)
- include a dummy empty source map in the extension
- edit the js file to remove the reference to the source map; must be done as part of the build; best option

**Comment by luckyrat** [comment] 2023-08-18 22:43
Duplicate of #248 

I think Mozilla's more relaxed recent attitude to modern development stacks means this is no longer an issue, at least once v3.10+ can be rolled out to Chrome users as well as Firefox.

**Closed by luckyrat** 2023-08-18 22:43 UTC
